services:
  influxdb:
    image: influxdb:2.7.10-alpine
    env_file:
      - influxdb2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

volumes:
  influxdb2:
    name: influxdb2